name: Publish Website

on:
  push:
    branches:
      - trunk
  workflow_dispatch:
jobs:
  Build-Artifact-Action:
    name: Build-Artifact-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install PHP dependencies
      uses: php-actions/composer@v6
      with:
        dev: no
        php_version: 8.1

    - name: Setup node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Upload the artifact
      uses: actions/upload-artifact@v4
      with:
        name: repository-artifact
        path: |
          ./plugin-name/
          ./plugin-name/!.DS_Store
          ./plugin-name/!.git 
          ./plugin-name/!.gitattributes 
          ./plugin-name/!.github 
          ./plugin-name/!.gitignore 
          ./plugin-name/!.editorconfig.json 
          ./plugin-name/!README.md 
          ./plugin-name/!composer.lock 
          ./plugin-name/!package-lock.json 
          ./plugin-name/!package.json 
          ./plugin-name/!travis.yml 
          ./plugin-name/!phpcs.xml.dist 
          ./plugin-name/!node_modules 
          ./plugin-name/!yarn.lock
